version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend/BookListApi
      dockerfile: Dockerfile
    container_name: booklist-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Azure connection strings should be provided via environment variables
      - ConnectionStrings__CosmosDb=${COSMOS_DB_CONNECTION_STRING}
      - ConnectionStrings__BlobStorage=${BLOB_STORAGE_CONNECTION_STRING}
    networks:
      - booklist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend/book-list-app
      dockerfile: Dockerfile
    container_name: booklist-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - booklist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  booklist-network:
    driver: bridge
