apiVersion: v1
kind: Namespace
metadata:
  name: booklist
  labels:
    name: booklist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booklist-config
  namespace: booklist
data:
  # These will be replaced by the CI/CD pipeline
  COSMOS_DB_CONNECTION_STRING: "PLACEHOLDER_COSMOS_DB_CONNECTION_STRING"
  BLOB_STORAGE_CONNECTION_STRING: "PLACEHOLDER_BLOB_STORAGE_CONNECTION_STRING"
---
apiVersion: v1
kind: Secret
metadata:
  name: booklist-secrets
  namespace: booklist
type: Opaque
stringData:
  # These will be replaced by the CI/CD pipeline with base64 encoded values
  cosmos-db-connection: "PLACEHOLDER_COSMOS_DB_CONNECTION_STRING"
  blob-storage-connection: "PLACEHOLDER_BLOB_STORAGE_CONNECTION_STRING"