apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booklist-api-hpa
  namespace: booklist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booklist-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booklist-frontend-hpa
  namespace: booklist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booklist-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80